name: flutter_left_right_container
description: A dual-pane layout widget featuring customizable start/end containers with smooth animated collapse, expansion states, and automatic dimension-tracking capabilities.
version: 0.9.4
resolution: workspace
homepage: https://o7planning.github.io

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_artist_core: ^1.0.0
  flutter_artist_styles: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

# -------------------------------------------------------
# dependency_overrides:
# -------------------------------------------------------
